language: ruby
before_install: gem install bundler -v 1.17.3
script: ./build.sh
branches:
  only:
  - master
rvm:
- 2.1.2
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
    secure: ePWiY2vaeROqJne0JeMsJ9TuPcfOyomUT/24jOPMIVcEkaRhGbRn6JULR646xe4GnZG9t0KnTuVOtyJshcWfBHhGI9DmScSahM69xw/0/g8IbcwLOoPj49atNiBxpi7dhUNf1u5LnM2e6SmE0TaHyhcJKMAv/umCzp1UAsFL9OweyMhq6ExsQU+X/pX7ru+kCGFWMi52svm1i3F9Cp1+99cse8SEt7vmCDPguANIXYOxTsu10POZZS87NnLNwlebwsVHrPjFP0g5aEMCCYy1IYMmPiUF0B3KxyA4085Ogieq1ccr4u0csrD57d+WkVT8jlMebqN9lWIEIHjC6vLT2xh5gjp5Hc33CTmChGW7LN/585A6+/7GSGI9nHZ5NjuPS9I2+hdOQqf241cgfnEtz2zIoh9wZSE+02IjDOFSIEV1+dWFesoJ/nY52/MA0m7jEwZVOSu9+d1NClDC/Nes9e3Usb3rW8Bh3bHWBOoda5dL87Q+D1z3M1cqMRvXKijjTB6eLQ9nlaMC949KJ4gfEQ92RTlI4GtBByRK3bf49REV7MKIvf0L22LdZsRDPkF3eYcp3VgmXyRhu7DogNZHbBiJzPY8JFqIlNZ/K9TT860DAQv5g8G1PmCfAKokA7uEFJJuQn2ahPJOSeuGNP8ozpfVKZvW6qtzs6w2hqwdGJk=